In [4]:
import pandas as pd 
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
import math 
import time 
import os
import sys 
import pathlib

In [5]:
df = pd.read_csv("/home/dhruv/Documents/NCF/NCF_Recommendation/NCF_Pytorch/train_data.csv")
df.head()

   UserID  ItemID  Rating  Timestamp
0       0      32       4  978824330
1       0      34       4  978824330
2       0       4       5  978824291
3       0      35       4  978824291
4       0      30       4  978824291

In [10]:
new_df = df.groupby("UserID").count().reset_index()
new_df

      UserID  ItemID  Rating  Timestamp
0          0      52      52         52
1          1     128     128        128
2          2      50      50         50
3          3      20      20         20
4          4     197     197        197
...      ...     ...     ...        ...
6035    6035     887     887        887
6036    6036     201     201        201
6037    6037      19      19         19
6038    6038     122     122        122
6039    6039     340     340        340

[6040 rows x 4 columns]

In [11]:
new_df["ItemID"].max()

np.int64(2313)